/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guia5;

import com.jtattoo.plaf.acryl.AcrylLookAndFeel;

import static java.lang.Integer.parseInt;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.filechooser.FileFilter;
import java.io.File;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author manuel
 * TO DO:
 * -agregar las graficas del historico
 * -agregar la importacion de excel
 */
public class Promedios extends javax.swing.JFrame {
    LinkedList notas = new LinkedList<>();  
    String nombre="";
    double aprobo=0,reprobo=0;//contadores de la gente que paso o reprobo
    double totEst;//total de estudiantes en la tabla
    /**
     * Creates new form NewJFrame
     */
    public Promedios() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datosTabla = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        GraficoTorta = new javax.swing.JButton();
        numeroNot = new javax.swing.JTextArea();
        numeroEst = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        crearTabla = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDefinitivas = new javax.swing.JTable();
        importExc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        borrTab = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        calcularDefinitivas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nombreEst = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        mostrarHistorico = new javax.swing.JButton();
        export = new javax.swing.JButton();
        guardarGrafico = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        datosTabla.setBackground(java.awt.Color.lightGray);
        try {
            // Establecer el Look and Feel del sistema
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        FileFilter filter = new FileFilter() {
            public boolean accept(File file) {
                // Aceptar todos los directorios y archivos .csv
                return file.isDirectory() || file.getName().toLowerCase().endsWith(".csv");
            }

            public String getDescription() {
                // Descripción del filtro
                return "Archivos CSV (*.csv)";
            }
        };

        // Aplicar el filtro al JFileChooser
        datosTabla.setFileFilter(filter);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad de notas: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, 20));

        GraficoTorta.setBackground(new java.awt.Color(0, 0, 102));
        GraficoTorta.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        GraficoTorta.setForeground(new java.awt.Color(255, 255, 255));
        GraficoTorta.setText("Mostrar taza de mortalidad");
        GraficoTorta.setBorder(null);
        GraficoTorta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GraficoTorta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GraficoTorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraficoTortaActionPerformed(evt);
            }
        });
        jPanel2.add(GraficoTorta, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 319, 189, 40));

        numeroNot.setBackground(new java.awt.Color(51, 51, 51));
        numeroNot.setColumns(20);
        numeroNot.setFont(new java.awt.Font("Hack Nerd Font Propo", 0, 12)); // NOI18N
        numeroNot.setForeground(new java.awt.Color(255, 255, 255));
        numeroNot.setLineWrap(true);
        numeroNot.setRows(1);
        numeroNot.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        numeroNot.setCaretColor(new java.awt.Color(255, 255, 255));
        numeroNot.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(numeroNot, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 81, 20));

        numeroEst.setBackground(new java.awt.Color(51, 51, 51));
        numeroEst.setColumns(20);
        numeroEst.setFont(new java.awt.Font("Hack Nerd Font Propo", 0, 12)); // NOI18N
        numeroEst.setForeground(new java.awt.Color(255, 255, 255));
        numeroEst.setLineWrap(true);
        numeroEst.setRows(1);
        numeroEst.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        numeroEst.setCaretColor(new java.awt.Color(255, 255, 255));
        numeroEst.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        numeroEst.setDragEnabled(true);
        numeroEst.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(numeroEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 81, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cantidad de estudiantes: ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        crearTabla.setBackground(new java.awt.Color(0, 0, 102));
        crearTabla.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        crearTabla.setForeground(new java.awt.Color(255, 204, 255));
        crearTabla.setText("Crear Tabla");
        crearTabla.setBorder(null);
        crearTabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTablaActionPerformed(evt);
            }
        });
        crearTabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                crearTablaKeyPressed(evt);
            }
        });
        jPanel2.add(crearTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 120, 30));

        tablaDefinitivas.setBackground(new java.awt.Color(51, 51, 51));
        tablaDefinitivas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaDefinitivas.setFont(new java.awt.Font("Hack Nerd Font Mono", 1, 12)); // NOI18N
        tablaDefinitivas.setForeground(new java.awt.Color(255, 255, 255));
        tablaDefinitivas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Definitiva", "Resultado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaDefinitivas.setCellSelectionEnabled(true);
        tablaDefinitivas.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        tablaDefinitivas.setFillsViewportHeight(true);
        tablaDefinitivas.setSelectionBackground(new java.awt.Color(51, 0, 102));
        tablaDefinitivas.setSelectionForeground(new java.awt.Color(102, 255, 255));
        tablaDefinitivas.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tablaDefinitivas.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tablaDefinitivas.setShowGrid(true);
        tablaDefinitivas.setShowHorizontalLines(true);
        tablaDefinitivas.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tablaDefinitivas);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 377, 486, 196));

        importExc.setBackground(new java.awt.Color(0, 0, 102));
        importExc.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        importExc.setForeground(new java.awt.Color(255, 204, 255));
        importExc.setText("Importar tabla");
        importExc.setBorder(null);
        importExc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        importExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importExcActionPerformed(evt);
            }
        });
        jPanel2.add(importExc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 119, 30));

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setToolTipText("");
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jTable1.setFillsViewportHeight(true);
        jTable1.setSelectionBackground(new java.awt.Color(51, 0, 102));
        jTable1.setSelectionForeground(new java.awt.Color(51, 255, 255));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, 492, 162));

        borrTab.setBackground(new java.awt.Color(102, 0, 51));
        borrTab.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        borrTab.setForeground(new java.awt.Color(255, 204, 255));
        borrTab.setText("Borrar datos");
        borrTab.setBorder(null);
        borrTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrTabActionPerformed(evt);
            }
        });
        jPanel2.add(borrTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 121, 30));

        jLabel4.setFont(new java.awt.Font("Hack Nerd Font Propo", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Calculos Notas");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 15, -1, -1));

        calcularDefinitivas.setBackground(new java.awt.Color(0, 0, 102));
        calcularDefinitivas.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        calcularDefinitivas.setForeground(new java.awt.Color(255, 255, 255));
        calcularDefinitivas.setText("Calcular Definitivas");
        calcularDefinitivas.setBorder(null);
        calcularDefinitivas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calcularDefinitivas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        calcularDefinitivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularDefinitivasActionPerformed(evt);
            }
        });
        jPanel2.add(calcularDefinitivas, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 319, 189, 40));

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreEst.setBackground(new java.awt.Color(51, 51, 51));
        nombreEst.setColumns(20);
        nombreEst.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        nombreEst.setForeground(new java.awt.Color(255, 255, 255));
        nombreEst.setRows(5);
        nombreEst.setToolTipText("Nombre estudiante");
        nombreEst.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        nombreEst.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(nombreEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 28, 201, 31));

        jLabel3.setFont(new java.awt.Font("Hack Nerd Font Propo", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre estudiante:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, -1, -1));

        mostrarHistorico.setBackground(new java.awt.Color(102, 0, 153));
        mostrarHistorico.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        mostrarHistorico.setForeground(new java.awt.Color(255, 255, 255));
        mostrarHistorico.setText("Mostrar Historico");
        mostrarHistorico.setBorder(null);
        mostrarHistorico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarHistoricoActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 110, 40));

        export.setBackground(new java.awt.Color(83, 209, 19));
        export.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        export.setForeground(new java.awt.Color(0, 51, 51));
        export.setText("Exportar Tablas");
        export.setBorder(null);
        export.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        jPanel1.add(export, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 17, 127, 48));

        guardarGrafico.setBackground(new java.awt.Color(1, 0, 96));
        guardarGrafico.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        guardarGrafico.setForeground(new java.awt.Color(255, 255, 255));
        guardarGrafico.setText("Guardar imagen");
        guardarGrafico.setBorder(null);
        guardarGrafico.setHideActionText(true);
        guardarGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarGraficoActionPerformed(evt);
            }
        });
        jPanel1.add(guardarGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 120, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 585, -1, -1));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        Salir.setBackground(new java.awt.Color(191, 36, 57));
        Salir.setFont(new java.awt.Font("Hack Nerd Font Propo", 0, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.setBorder(null);
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel3.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 640, 110, 37));

        jLabel6.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 530, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia5/imagenes/13167.jpg"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1080, 704));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarGraficoActionPerformed

    }//GEN-LAST:event_guardarGraficoActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        String userHome = System.getProperty("user.home");//obtiene direccion para guardar lo datos
        SimpleDateFormat Formato = new SimpleDateFormat("yyyyMMdd_HHmmss");//formato de hora
        Date Datos = new Date();//obtiene la hora
        String strDate = Formato.format(Datos);//mete la hora en un string
        String GuarNombre = userHome + "\\Documents\\Tabla_Resultados_ " + strDate + ".csv";//crea la direccion
        DefaultTableModel definitivas = (DefaultTableModel) tablaDefinitivas.getModel();//instancia el modelo de la tabla de definitivas
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try {
            FileWriter writer = new FileWriter(GuarNombre);//objeto para escribir
            //guarda la primera tabla
            // Escribir los encabezados del CSV
            for (int i = 0; i < model.getColumnCount(); i++) {
                writer.write(model.getColumnName(i) + ",");
            }
            writer.write("\n");
            // Escribir los datos de la tabla en el CSV
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    writer.write(model.getValueAt(i, j).toString() + ",");
                }
                writer.write("\n");
            }
            writer.write("\n");
            //guarda los datos de la segunda tabla
            // Escribir los encabezados del CSV
            for (int i = 0; i < definitivas.getColumnCount(); i++) {
                writer.write(definitivas.getColumnName(i) + ",");
            }
            writer.write("\n");
            // Escribir los datos de la tabla en el CSV
            for (int i = 0; i < definitivas.getRowCount(); i++) {
                for (int j = 0; j < definitivas.getColumnCount(); j++) {
                    writer.write(definitivas.getValueAt(i, j).toString() + ",");
                }
                writer.write("\n");
            }
            writer.close();
            System.out.println("Datos exportados exitosamente en " + GuarNombre);
        } catch (Exception e) {
            System.out.println("No se pudo exportar la tabla");
            e.printStackTrace();
        }
    }//GEN-LAST:event_exportActionPerformed

    private void mostrarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarHistoricoActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int noes = 0;
        notas.removeAll(notas);
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).toString().equals(nombreEst.getText())) {
                nombre = model.getValueAt(i, 0).toString();
                for (int j = 1; j < model.getColumnCount(); j++) {//cambie el for para poder pasar notas de string a double
                    try {
                        Double valor = Double.valueOf(model.getValueAt(i, j).toString());
                        notas.add(valor);
                    } catch (NumberFormatException e) {
                        System.err.println("Error al pasar datos");
                        e.printStackTrace();
                    }
                }
            } else {
                noes++;
            }
        }
        if (noes == model.getRowCount()) {
            MensajeError menErr = new MensajeError(this, true);
            menErr.setVisible(true);
            nombreEst.setText("");
        }else{
            Graficas.CrearGuardarGrafica(nombre, notas, guardarGrafico.isSelected()); //los datos viajan al main para generar la imagen
            ImageIcon ImagenEstudiante = new ImageIcon("src/guia5/imagenes/Estudiante.jpg");
            ImagenEstudiante.getImage().flush();
            this.jLabel6.setIcon(ImagenEstudiante);
        }
    }//GEN-LAST:event_mostrarHistoricoActionPerformed

    private void calcularDefinitivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularDefinitivasActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel definitivas = (DefaultTableModel) tablaDefinitivas.getModel();
        try{
            for (int i = 0; i < model.getRowCount(); i++) {
                double suma=0;
                String nombre = model.getValueAt(i, 0).toString();
                //obtiene los datos y calcula la definitiva para ponerla en la tabla
                for (int j = 1; j < model.getColumnCount(); j++) {
                    double nota;
                    nota = Double.parseDouble(model.getValueAt(i, j).toString());
                    if(nota<=5)
                    suma += nota;
                    else
                    throw new Exception("La nota ingresada es invalida");
                }
                double definitiva = suma / (model.getColumnCount()-1);
                String paso;
                if (definitiva >= 3.0) {
                    paso="APROBO";
                    aprobo++;
                }else{
                    paso="REPROBO";
                    reprobo++;
                }
                definitivas.addRow(new Object[]{nombre, definitiva, paso});
                totEst=model.getRowCount();
            }
        }catch(Exception e){
            System.err.println("Hubo un problema al calcular definitivas");
            e.printStackTrace();
            borrTabActionPerformed(evt);
        }
    }//GEN-LAST:event_calcularDefinitivasActionPerformed

    private void borrTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrTabActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel definitivas = (DefaultTableModel) tablaDefinitivas.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        definitivas.setRowCount(0);
        aprobo=0;
        reprobo=0;
        numeroEst.setText("");
        numeroNot.setText("");
        jLabel5.setIcon(null);
        jLabel6.setIcon(null);
        
    }//GEN-LAST:event_borrTabActionPerformed

    private void importExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importExcActionPerformed
        JFileChooser escogerArchivo = new JFileChooser();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String linea;
        String[] estudiantes = null;
        Boolean primera = false;
        int returnValue = escogerArchivo.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File archivo = escogerArchivo.getSelectedFile();
            try {
                //ingresa archivo a tabla
                Scanner entrada = new Scanner(archivo);
                // objeto para procesar información
                entrada.nextLine();//salta la primera linea de etiquetas
                while (entrada.hasNext()) {
                    linea = entrada.nextLine();
                    if(linea.contains(";")){
                        estudiantes = linea.split(";");
                        System.out.println(";");
                    }else if(linea.contains(","))
                    estudiantes = linea.split(",");
                    if (!primera) {
                        model.addColumn("Nombre:");
                        for (int i = 1; i < estudiantes.length; i++) {
                            model.addColumn("Nota " + i);
                        }
                        primera = true;
                    }
                    model.addRow(estudiantes);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Promedios.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_importExcActionPerformed

    private void crearTablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_crearTablaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearTablaKeyPressed

    private void crearTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTablaActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try{
            int est, not;
            est = parseInt(numeroEst.getText());
            not = parseInt(numeroNot.getText());
            model.addColumn("Nombre");
            model.setRowCount(est);
            for (int i = 1; i < not+1; i++) {
                model.addColumn("Nota:" + i);
            }
        }catch(Exception e){
            System.err.println("Hubo un problema al crear la tabla");
            numeroEst.setText("");
            numeroNot.setText("");
            e.printStackTrace();
        }
    }//GEN-LAST:event_crearTablaActionPerformed

    private void GraficoTortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraficoTortaActionPerformed
        Graficas.torta(aprobo, reprobo, totEst);
        ImageIcon ImagenTorta = new ImageIcon("src/guia5/imagenes/TORTA.jpg");
//        ImageIcon ImagenTorta = new ImageIcon("");
//        ponga su direccion para guardar las imagenes y pone mi direccion en comentarios
//        O MEJOR LO DEJA DENTRO DE LAS IMAGENES DEL PROYECTO PARA QUE SEA UNIVERSAL es decir esa ubicacion (con amor)
        ImagenTorta.getImage().flush();
        this.jLabel5.setIcon(ImagenTorta);
    }//GEN-LAST:event_GraficoTortaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        boolean nimbusSet = false;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Promedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Promedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Promedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Promedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            if (!nimbusSet) {
                try {
                    UIManager.setLookAndFeel(new AcrylLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Promedios.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            new Promedios().setVisible(true);
        }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GraficoTorta;
    private javax.swing.JButton Salir;
    private javax.swing.JButton borrTab;
    private javax.swing.JButton calcularDefinitivas;
    private javax.swing.JButton crearTabla;
    private javax.swing.JFileChooser datosTabla;
    private javax.swing.JButton export;
    private javax.swing.JCheckBox guardarGrafico;
    private javax.swing.JButton importExc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton mostrarHistorico;
    private javax.swing.JTextArea nombreEst;
    private javax.swing.JTextArea numeroEst;
    private javax.swing.JTextArea numeroNot;
    private javax.swing.JTable tablaDefinitivas;
    // End of variables declaration//GEN-END:variables

    private static class JLabel5 {

        public JLabel5() {
        }
    }
}
